### ISSUE TITLE
plots crashes on startup

### ISSUE THREAD

**Issue by Fabus1184** [alexhuntley/Plots#123]
When starting plots it crashed with the following error:
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/plots/plots.py", line 145, in do_activate
    self.add_equation(None, record=False)
  File "/usr/lib/python3.10/site-packages/plots/plots.py", line 242, in add_equation
    row = formularow.FormulaBox(self)
  File "/usr/lib/python3.10/site-packages/plots/formularow.py", line 256, in __init__
    self.color_picker = colorpicker.PopoverColorPicker()
  File "/usr/lib/python3.10/site-packages/plots/colorpicker.py", line 52, in __init__
    self.update_color()
  File "/usr/lib/python3.10/site-packages/plots/colorpicker.py", line 57, in update_color
    self.provider.load_from_data(css.encode())
TypeError: Gtk.CssProvider.load_from_data() takes exactly 3 arguments (2 given)
```

installed packages with versions: https://pastebin.com/Lmzm7667

**Comment by alexhuntley** [comment]
Thank you! Something changed in PyGObject, but not sure when exactly.

**Comment by Seren541** [comment]
Has a solution been found? Still happening for me on Arch.

**Comment by Fabus1184** [comment]
Commit c21bb3c fixes it

**Comment by Seren541** [comment]
Can someone push it to the aur? It hasn't been updated for a while it seems.
https://aur.archlinux.org/packages/plots
