### ISSUE TITLE
Blue Screen

### ISSUE THREAD

**Issue by the-zero885** [alexhuntley/Plots#13]
Hello! I install the program in Linux Mint 20.1 way PPA and don't work, appears a blue screen.

![Captura de pantalla de 2021-02-15 21-08-39](https://user-images.githubusercontent.com/64677777/108006533-17eaa100-6fd2-11eb-8600-321bc8978fe3.png)

**Comment by alexhuntley** [comment]
Hi, could you please run the command `plots` in a terminal and copy the output here?

**Comment by the-zero885** [comment]
> Hi, could you please run the command `plots` in a terminal and copy the output here?

cesar@cesar-Lenovo-G460:~$ plots
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/plots/plots.py", line 214, in gl_realize
    self.vertex_shader = shaders.compileShader(
  File "/usr/lib/python3/dist-packages/OpenGL/GL/shaders.py", line 220, in compileShader
    raise RuntimeError(
RuntimeError: ("Shader compile failure (0): b'0:20(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, and 1.00 ES\\n'", [b'/*\n   Copyright 2021 Alexander Huntley\n\n   This file is part of Plots.\n\n   Plots is free software: you can redistribute it and/or modify\n   it under the terms of the GNU General Public License as published by\n   the Free Software Foundation, either version 3 of the License, or\n   (at your option) any later version.\n\n   Plots is distributed in the hope that it will be useful,\n   but WITHOUT ANY WARRANTY; without even the implied warranty of\n   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\n   GNU General Public License for more details.\n\n   You should have received a copy of the GNU General Public License\n   along with Plots.  If not, see <https://www.gnu.org/licenses/>.\n*/\n\n#version 330 core\nlayout (location = 0) in vec3 position;\nout vec2 graph_pos;\nuniform vec2 viewport;\nuniform vec2 translation;\nuniform float scale;\n\nvoid main() {\n    gl_Position = vec4(position, 1.0);\n    vec2 normalised = position.xy * viewport / viewport.x;\n    graph_pos = normalised*scale - translation;\n}'], GL_VERTEX_SHADER)
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No existe el archivo o el directorio: '/var/crash/_usr_bin_plots.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/plots/plots.py", line 214, in gl_realize
    self.vertex_shader = shaders.compileShader(
  File "/usr/lib/python3/dist-packages/OpenGL/GL/shaders.py", line 220, in compileShader
    raise RuntimeError(
RuntimeError: ("Shader compile failure (0): b'0:20(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, and 1.00 ES\\n'", [b'/*\n   Copyright 2021 Alexander Huntley\n\n   This file is part of Plots.\n\n   Plots is free software: you can redistribute it and/or modify\n   it under the terms of the GNU General Public License as published by\n   the Free Software Foundation, either version 3 of the License, or\n   (at your option) any later version.\n\n   Plots is distributed in the hope that it will be useful,\n   but WITHOUT ANY WARRANTY; without even the implied warranty of\n   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\n   GNU General Public License for more details.\n\n   You should have received a copy of the GNU General Public License\n   along with Plots.  If not, see <https://www.gnu.org/licenses/>.\n*/\n\n#version 330 core\nlayout (location = 0) in vec3 position;\nout vec2 graph_pos;\nuniform vec2 viewport;\nuniform vec2 translation;\nuniform float scale;\n\nvoid main() {\n    gl_Position = vec4(position, 1.0);\n    vec2 normalised = position.xy * viewport / viewport.x;\n    graph_pos = normalised*scale - translation;\n}'], GL_VERTEX_SHADER)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/plots/plots.py", line 195, in gl_render
    shaders.glUseProgram(self.shader)
AttributeError: 'Plots' object has no attribute 'shader'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No existe el archivo o el directorio: '/var/crash/_usr_bin_plots.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/plots/plots.py", line 195, in gl_render
    shaders.glUseProgram(self.shader)
AttributeError: 'Plots' object has no attribute 'shader'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/plots/plots.py", line 195, in gl_render
    shaders.glUseProgram(self.shader)
AttributeError: 'Plots' object has no attribute 'shader'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No existe el archivo o el directorio: '/var/crash/_usr_bin_plots.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/plots/plots.py", line 195, in gl_render
    shaders.glUseProgram(self.shader)
AttributeError: 'Plots' object has no attribute 'shader'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/plots/plots.py", line 195, in gl_render
    shaders.glUseProgram(self.shader)
AttributeError: 'Plots' object has no attribute 'shader'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No existe el archivo o el directorio: '/var/crash/_usr_bin_plots.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/plots/plots.py", line 195, in gl_render
    shaders.glUseProgram(self.shader)
AttributeError: 'Plots' object has no attribute 'shader'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/plots/plots.py", line 195, in gl_render
    shaders.glUseProgram(self.shader)
AttributeError: 'Plots' object has no attribute 'shader'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No existe el archivo o el directorio: '/var/crash/_usr_bin_plots.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/plots/plots.py", line 195, in gl_render
    shaders.glUseProgram(self.shader)
AttributeError: 'Plots' object has no attribute 'shader'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/plots/plots.py", line 195, in gl_render
    shaders.glUseProgram(self.shader)
AttributeError: 'Plots' object has no attribute 'shader'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No existe el archivo o el directorio: '/var/crash/_usr_bin_plots.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/plots/plots.py", line 195, in gl_render
    shaders.glUseProgram(self.shader)
AttributeError: 'Plots' object has no attribute 'shader'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/plots/plots.py", line 195, in gl_render
    shaders.glUseProgram(self.shader)
AttributeError: 'Plots' object has no attribute 'shader'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No existe el archivo o el directorio: '/var/crash/_usr_bin_plots.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/plots/plots.py", line 195, in gl_render
    shaders.glUseProgram(self.shader)
AttributeError: 'Plots' object has no attribute 'shader'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/plots/plots.py", line 195, in gl_render
    shaders.glUseProgram(self.shader)
AttributeError: 'Plots' object has no attribute 'shader'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No existe el archivo o el directorio: '/var/crash/_usr_bin_plots.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/plots/plots.py", line 195, in gl_render
    shaders.glUseProgram(self.shader)
AttributeError: 'Plots' object has no attribute 'shader'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/plots/plots.py", line 195, in gl_render
    shaders.glUseProgram(self.shader)
AttributeError: 'Plots' object has no attribute 'shader'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No existe el archivo o el directorio: '/var/crash/_usr_bin_plots.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/plots/plots.py", line 195, in gl_render
    shaders.glUseProgram(self.shader)
AttributeError: 'Plots' object has no attribute 'shader'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/plots/plots.py", line 195, in gl_render
    shaders.glUseProgram(self.shader)
AttributeError: 'Plots' object has no attribute 'shader'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No existe el archivo o el directorio: '/var/crash/_usr_bin_plots.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/plots/plots.py", line 195, in gl_render
    shaders.glUseProgram(self.shader)
AttributeError: 'Plots' object has no attribute 'shader'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/plots/plots.py", line 195, in gl_render
    shaders.glUseProgram(self.shader)
AttributeError: 'Plots' object has no attribute 'shader'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No existe el archivo o el directorio: '/var/crash/_usr_bin_plots.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/plots/plots.py", line 195, in gl_render
    shaders.glUseProgram(self.shader)
AttributeError: 'Plots' object has no attribute 'shader'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/plots/plots.py", line 195, in gl_render
    shaders.glUseProgram(self.shader)
AttributeError: 'Plots' object has no attribute 'shader'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No existe el archivo o el directorio: '/var/crash/_usr_bin_plots.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/plots/plots.py", line 195, in gl_render
    shaders.glUseProgram(self.shader)
AttributeError: 'Plots' object has no attribute 'shader'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/plots/plots.py", line 195, in gl_render
    shaders.glUseProgram(self.shader)
AttributeError: 'Plots' object has no attribute 'shader'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No existe el archivo o el directorio: '/var/crash/_usr_bin_plots.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/plots/plots.py", line 195, in gl_render
    shaders.glUseProgram(self.shader)
AttributeError: 'Plots' object has no attribute 'shader'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/plots/plots.py", line 195, in gl_render
    shaders.glUseProgram(self.shader)
AttributeError: 'Plots' object has no attribute 'shader'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No existe el archivo o el directorio: '/var/crash/_usr_bin_plots.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/plots/plots.py", line 195, in gl_render
    shaders.glUseProgram(self.shader)
AttributeError: 'Plots' object has no attribute 'shader'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/plots/plots.py", line 195, in gl_render
    shaders.glUseProgram(self.shader)
AttributeError: 'Plots' object has no attribute 'shader'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No existe el archivo o el directorio: '/var/crash/_usr_bin_plots.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/plots/plots.py", line 195, in gl_render
    shaders.glUseProgram(self.shader)
AttributeError: 'Plots' object has no attribute 'shader'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/plots/plots.py", line 195, in gl_render
    shaders.glUseProgram(self.shader)
AttributeError: 'Plots' object has no attribute 'shader'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No existe el archivo o el directorio: '/var/crash/_usr_bin_plots.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/plots/plots.py", line 195, in gl_render
    shaders.glUseProgram(self.shader)
AttributeError: 'Plots' object has no attribute 'shader'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/plots/plots.py", line 195, in gl_render
    shaders.glUseProgram(self.shader)
AttributeError: 'Plots' object has no attribute 'shader'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No existe el archivo o el directorio: '/var/crash/_usr_bin_plots.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/plots/plots.py", line 195, in gl_render
    shaders.glUseProgram(self.shader)
AttributeError: 'Plots' object has no attribute 'shader'

**Comment by alexhuntley** [comment]
Looks like your laptop doesn't support OpenGL 3.3. At the moment this is a requirement of Plots sadly.

In the short term I'll display an error if this is detected. Long term a fallback/software renderer may be desirable.

**Comment by alexhuntley** [comment]
a535c3d now shows a warning when OpenGL < 3.3 is detected.
