### ISSUE TITLE
Zooming out too far causes Plots to crash

### ISSUE THREAD

**Issue by Newbytee** [alexhuntley/Plots#73]
I can easily reproduce this by spinning up my scroll wheel and letting it do its thing for a few seconds. Here's the traceback:

```
$ com.github.alexhuntley.Plots 
/app/lib/python3.9/site-packages/plots/graph.py:162: RuntimeWarning: overflow encountered in multiply
  graph_extent = 2*self.viewport/self.viewport[0]*self.scale
Traceback (most recent call last):
  File "/app/lib/python3.9/site-packages/plots/graph.py", line 148, in gl_render
    self.render()
  File "/app/lib/python3.9/site-packages/plots/graph.py", line 175, in render
    major_grid, minor_grid = self.major_grid(pixel_extent[0])
  File "/app/lib/python3.9/site-packages/plots/graph.py", line 85, in major_grid
    exponent = math.floor(math.log10(abs(min_extent)))
OverflowError: cannot convert float infinity to integer
```

**Comment by alexhuntley** [comment]
Related to #58. Probably need to impose some limits on zooming, but not sure how to calculate these.

**Comment by Agvantibo** [comment]
Can confirm, zooming in too far also makes Plots behave weirdly and crash.
