### ISSUE TITLE
Crash on typing "sum"

### ISSUE THREAD

**Issue by matbme** [alexhuntley/Plots#75]
When I type "sum" into an equation, the application crashes with the following error:

```
Traceback (most recent call last):
  File "/app/lib/python3.9/site-packages/plots/formularow.py", line 304, in edited
    body, expr = self.editor.expr.to_glsl()
  File "/app/lib/python3.9/site-packages/plots/elements/elements.py", line 338, in to_glsl
    sum_body, sum_expr = sums.pop().to_glsl("".join(body_stack.pop()),
  File "/app/lib/python3.9/site-packages/plots/elements/sum.py", line 53, in to_glsl
    assert var.isidentifier()
```

Running the latest flatpak version (0.8.1).

**Comment by alexhuntley** [comment]
Thanks for the catch. I've fixed it in 9f2ce43, which will be in the next release.
