### ISSUE TITLE
Crash when typing "^" in an empty equation

### ISSUE THREAD

**Issue by bsoelch** [alexhuntley/Plots#77]
The application crashes when typing "^" into an empty equation

Traceback:

```
Traceback (most recent call last):
  File "/app/lib/python3.9/site-packages/plots/formularow.py", line 304, in edited
    body, expr = self.editor.expr.to_glsl()
  File "/app/lib/python3.9/site-packages/plots/elements/elements.py", line 307, in to_glsl
    string_stack[-1].insert(i, "mypow(")
UnboundLocalError: local variable 'i' referenced before assignment
```

Version:
0.8.2 (flatpak)

**Comment by alexhuntley** [comment]
Nice catch, thanks! Should be fixed now.
