### ISSUE TITLE
Crash when pasting syntactically incorrect equations

### ISSUE THREAD

**Issue by bsoelch** [alexhuntley/Plots#78]
For instance pasting `crash¡` into an equation field leads to a crash with the following traceback: 

```
Traceback (most recent call last):
  File "/app/lib/python3.9/site-packages/plots/cursor.py", line 98, in paste_cb
    elements = parser.from_latex(text)
  File "/app/lib/python3.9/site-packages/plots/parser.py", line 138, in from_latex
    return transformer.transform(latex_parser.parse(string))
  File "/app/lib/python3.9/site-packages/lark/lark.py", line 625, in parse
    return self.parser.parse(text, start=start, on_error=on_error)
  File "/app/lib/python3.9/site-packages/lark/parser_frontends.py", line 96, in parse
    return self.parser.parse(stream, chosen_start, **kw)
  File "/app/lib/python3.9/site-packages/lark/parsers/earley.py", line 266, in parse
    to_scan = self._parse(lexer, columns, to_scan, start_symbol)
  File "/app/lib/python3.9/site-packages/lark/parsers/xearley.py", line 146, in _parse
    to_scan = scan(i, to_scan)
  File "/app/lib/python3.9/site-packages/lark/parsers/xearley.py", line 119, in scan
    raise UnexpectedCharacters(stream, i, text_line, text_column, {item.expect.name for item in to_scan},
lark.exceptions.UnexpectedCharacters: No terminal matches '¡' in the current parser context, at line 1 col 6

crash¡
     ^
Expected one of: 
	* MINUS
	* __ANON_4
	* PAREN
	* EQUAL
	* UNDERSCORE
	* DIGIT
	* __ANON_3
	* __ANON_0
	* __ANON_1
	* __ANON_5
	* GREEK
	* __ANON_7
	* __ANON_2
	* CIRCUMFLEX
	* PLUS
	* SYMBOL
	* TIMES
	* __ANON_6
	* LETTER
```

Version:
0.8.2 (flatpak)

**Comment by alexhuntley** [comment]
Thank you! Should be fixed now.
