### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by martin-desktops** [alexhuntley/Plots#97]
# Describe the bug
Freshly installed Plots app doesn't open. While running Plots with Termianl: (flatpak run com.github.alexhuntley.Plots) there is the following error:

```
[martin@fedora ~]$ flatpak run com.github.alexhuntley.Plots

(process:2): Gtk-WARNING **: 17:20:19.820: Locale not supported by C library.
	Using the fallback 'C' locale.
Traceback (most recent call last):
  File "/app/bin/plots", line 8, in <module>
    sys.exit(main())
  File "/app/lib/python3.9/site-packages/plots/__init__.py", line 22, in main
    plots.Plots().run(sys.argv)
  File "/app/lib/python3.9/site-packages/plots/plots.py", line 42, in __init__
    plots.i18n.bind()
  File "/app/lib/python3.9/site-packages/plots/i18n.py", line 26, in bind
    locale.setlocale(locale.LC_ALL, "")
  File "/usr/lib/python3.9/locale.py", line 610, in setlocale
    return _setlocale(category, locale)

```

# Additional information:
Plots 0.8.4 (Flathub)
OS: Fedora Silverblue 37 (Beta)
GNOME 43.0
Wayland

**Comment by martin-desktops** [comment]
I cannot reproduce the issue anymore!
